### ISSUE TITLE
bmson importing doesn't work

### ISSUE THREAD

**Issue by DolphinDTM** [CircularRhythm/CircularRhythm#12]
Dragging and dropping the folder containing my bmson file into the CircularRhythm tab doesn't load the charts.  
Currently using Google Chrome, trying to import a bmson v1.0 with mode-hint set to "circularrhythm-single"

**Comment by suitougreentea** [comment]
Can you send me an archived folder? I'll investigate it.

**Comment by DolphinDTM** [comment]
I'll send it via Twitter DM

**Comment by suitougreentea** [comment]
I found there is a bug that the game aborts importing when it finds unsupported bmson (in this case it is "beat-7k" data).
I'm sorry to trouble you, but please create another folder which contains only CircularRhythm bmson to test it.
In addition, the game emits error if "stop_events" is undefined.

Fixing of these might be late, sorry.

**Comment by DolphinDTM** [comment]
I see! I will try again!
